logging:  level:    root: DEBUG

spring:
  datasource:
    druid:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;mode=mysql
      username: sa
      password: 
  mail:
    host: 
    port: 465
    username: 
    password: 

pagehelper:
  helper-dialect: h2

wechat:
  app-id: 
  app-secret: 

jwt:  key: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
