server:  port: 8080  servlet:    context-path: /questionnaire    encoding:      enabled: true      charset: UTF-8      force: true  shutdown: gracefulmanagement:  health:    probes:      enabled: truespring:  profiles:    active: '@profileActive@'  lifecycle:    timeout-per-shutdown-phase: 20s
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8  servlet:    multipart:      max-request-size: 30MB
      max-file-size: 30MB  datasource:    druid:      initial-size: 2      min-idle: 2      max-active: 5      max-wait: 60000      time-between-eviction-runs-millis: 60000      validation-query: select 1      break-after-acquire-failure: true      connection-error-retry-attempts: 1      time-between-connect-error-millis: 5000      test-while-idle: true  mail:    properties:      mail:
        smtp:
          auth: true          starttls:
            enable: true
            required: true          ssl:            enable: true
